### ISSUE TITLE
mini lecteur de sons synchronisés avec des timers

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/cadexmus2#11]
On ne peut plus utiliser l'algorithme de cadexmus1 parce les notes étaient contenues dans une grille discrète (16 position possibles). Maintenant le but ce serait de permettre un positionnement continu des notes (comme dans la maquette).

Il faut faire un petit projet test qui vérifie que ce nouvel algo de lecture des sons fonctionne au moins autant bien que l'itératif de la version 1

**Comment by j4kim** [comment]
plutôt que de faire un projet à part j'ai directement fait le test dans la [maquette](https://github.com/HE-Arc/cadexmus2/blob/master/maquette/index.html), la lecture marche assez bien, en tous cas avec 6 lignes (et que sur chrome).
Il y a juste des problèmes de clics lorsqu'un sample est arrété mais je pense que c'est inévitable.. ou alors il faudrait faire des minis-fondus à la fin de chaque note pour qu'on entende pas ces clics mais ça devient lourd pour le programme je pense.

**Comment by greut** [comment]
Pas mal. Je remarque un petit problème intéressant quand on double-clic sur un élément existant.

``` js
$(".note").click(() => $(this).remove());
$(".line").dblclick(() => ...);
```

C'est encore plus flagrant si on change le premier `click` en un `dblclick`.

Qu'elle peut en être la raison?

_hint:_

``` html
<x class="line">
  <y class="note" />
</x>
```

**Comment by j4kim** [comment]
En effet, le clic est géré, donc ça supprime la note, puis le double clic est géré, donc ça en rajoute une.
Au départ je pensais faire l'inverse, cliquer pour créer et double-cliquer pour effacer, mais du coup c'était impossible d'effacer sans recréer.
Alors je me suis satisfait de cette solution, dans un deuxième temps on pourrait rajouter un bouton qui bascule d'un mode écriture au mode effacement (crayon et gomme)

**Comment by greut** [comment]
@j4kim le problème est que les évènements dans le DOM font des bulles... (traduction sauvage)
- https://en.wikipedia.org/wiki/DOM_events
- http://jsfiddle.net/cwtuan/je1g3f29/16/

Du coup, si vous n'appelez pas [stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation), les évènements sur le `.note` remontent au `.line`, etc. jusqu'à `html`.

Le bon côté du ceci est qu'il est possible de n'écouter que le conteneur et de faire ses tests à partir de [target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) avec `$.closest`.

**Comment by j4kim** [comment]
ah ok, cool merci. Du coup j'ai remis dblclick pour les deux

**Comment by greut** [comment]
N'oubliez pas que sur un téléphone mobile plein d'évènements n'existent pas, le plus fameux étant _hover_.

**Comment by j4kim** [comment]
¯\_(ツ)_/¯

**Comment by greut** [comment]
Une suite que j'envisagerais sur votre maquette est que l'HTML soit construit à partir d'une structure de données, type JSON. N'hésitez pas à simplifier les choses si nécessaire, e.g. en discrétisant le temps pour que ça ressemble plus à un tenori-on.

Au passage des examples qui utilisent l'api Web Audio.
- http://kevvv.in/mix/
- https://github.com/meenie/band.js
- https://www.html5rocks.com/en/tutorials/webaudio/intro/
- http://dinahmoelabs.com/plink

**Comment by j4kim** [comment]
- Construire à partir d'une structure de données
  - Comment ça ? Au final la page sera construite avec un template depuis les données récupérées en laravel
- tenori-on
  - la [v1](http://j4kim.nexgate.ch/trucs/cadexmus/seq.php?nomPartie=couou&temps=4&mesures=2) était comme ça, on a remarqué qu'il manquait la notion de durée d'une note. Pour des rithmes de batteries ça va bien mais quand il faut faire des mélodies on a tout de suite besoin de la durée.
- discrétiser
  - Je suis d'accord, je pensais fixer les notes sur une grille de 64 (l'unité minimale serait donc la quadruple-croche) plutôt que le pourcentage. Ca réglerait le problème de l'approximation quand on crée ou déplace une note.
- API web audio
  - Je pense que ce serait mieux que le simple élément DOM audio.
    Est-ce que ça vaut la peine de prendre du temps à s'y plonger ?
    Plink c'est hyper bien

**Comment by greut** [comment]
Je pense que ça vaut la peine oui.

https://github.com/goldfire/howler.js/tree/master/examples/sprite

**Comment by greut** [comment]
https://youtu.be/o1CX38C9WtM

**Comment by j4kim** [comment]
Joli ! Tout svg ?
Je vais reafire la version avec les div draggables, quand même plus pratique je pense.

**Comment by greut** [comment]
SVG oui et le bon moyen pour connaître le temps est d'utiliser le fameux `requestAnimationFrame`

``` js
window.requestAnimationFrame(function() {
    context.currentTime
    //...
})
```
