### ISSUE TITLE
Améliorations responsive design

### ISSUE THREAD

**Issue by matbandeli** [HE-Arc/cadexmus2#13]
- [x] menu responsive si taille écran petite : par exemple un bouton menu qui ouvre les options du menu principal

- [ ] taille du bouton créer un projet en mode moyen et petit de taille d'écran

- [ ] à côté du bouton play, pouvoir régler le volume. cela permettrait de mieux comprendre que le bouton play est pour la musqiue
et que ce n'est pas lié à une fonctionalité de menu déroulant

- [ ] quand la hauteur du device est petite, afficher le bouton "créer un projet en haut de la liste (pour qu'il soit visible),
puisque c'est une fonctionnalité importante

**Comment by j4kim** [comment]
@matbandeli merci pour ces propositions. J'ai juste pas bien compris la 2ème

**Comment by matbandeli** [comment]
la taille du bouton n'était pas approprié pour une taille d'écran petite ou moyenne il me semble (bouton trop large)

**Comment by greut** [comment]
https://www.smashingmagazine.com/2016/11/a-quick-guide-for-designing-better-buttons/
