### ISSUE TITLE
Créer une vue projet qui affiche les informations *d'un* projet

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/cadexmus2#22]
on doit pouvoir atteindre un projet avec une route du genre /projects/nom_du_projet

**Comment by j4kim** [comment]
la route /projects/nom_du_projet n'est pas facile car le nom du projet n'est pas unique... est-ce qu'il devrait l'être ? Il faudrait que la combinaison user-nom du projet soit unique mais pour l'instant le projet n'est pas lié à un utilisateur

**Comment by greut** [comment]
https://github.com/cviebrock/eloquent-sluggable
