### ISSUE TITLE
gérer la collision de deux nouvelles vesions d'un projet

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/cadexmus2#26]
si un utilisateur B crée une version 2 d'un projet alors qu'une autre version 2 existe déjà créée par un utilisateur A. Il faut essayer de merger les deux versions, si ça échoue, on se contentera de rejeter les modifications de l'utilisateur B.

**Comment by j4kim** [comment]
http://jsonpatch.com/
ou simplement http://php.net/manual/fr/function.array-merge.php ?

**Comment by greut** [comment]
C'est bien plus compliqué que ça, hélas.

* https://en.wikipedia.org/wiki/Operational_transformation
* https://github.com/josephg/ShareJS
* https://github.com/share/sharedb

**Comment by j4kim** [comment]
mais euh... 😢 
On pourrait utiliser ShareDB avec Laravel ? ou on refait tout avec DerbyJS ^^ ?
Apparemment c'est pour le vrai realtime, pour la version "update toutes les 2 s", jsonpatch peut faire le taf non ?

**Comment by greut** [comment]
Vous devriez utiliser le chat de @bastou2316 pour communiquer les modifications. Mais n'allez pas jusque là, c'est un problème qui se trouve au-delà de ce cours.

**Comment by greut** [comment]
Votre modèle réalise la persistance partielle et c'est suffisant. La persistance complète demanderait de le changer et quant à la persistance confluente... bonne chance.

https://www.youtube.com/watch?v=T0yzrZL1py0#t=8m50

Sinon, il y a ce papier sur un [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type): http://hal.upmc.fr/file/index/docid/555588/filename/techreport.pdf

Arrêtez-vous à la version : _« quelqu'un d'autre a modifié ce document entre temps ¯\\\_(ツ)\_/¯ »_

**Comment by j4kim** [comment]
D'accord... du coup on ne pourra carrément pas du tout modifier le morceau en même temps, on ferait pas mieux de retourner à un modèle où c'est la track qui est l'élément atomique, plutôt que le projet ? Ca permettrait au moins la modification de deux tracks en même temps

**Comment by greut** [comment]
@j4kim ça ne change rien. Ce que vous faites me semble correct, aller plus loin est simplement trop compliqué.

Pour vous en convaincre écrivez un test unitaire avec un scénario d'édition concurrente.
