### ISSUE TITLE
Chat : récupération uniquement des nouveaux messages

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/cadexmus2#43]
Voilà comment j'imagine ça :
- première connexion du client, il reçoit tous les messages (ou les 30 derniers) + un timestamp du serveur
- le client garde le timestamp en local
- 3 secondes plus tard, il refait une requête en donnant le timestamp
- le serveur récupère les messages plus vieux que ce timestamp et les renvoie (ou rien si y en a pas) + un nouveau timestamp
ainsi de suite

**Comment by greut** [comment]
Ce n'est pas comme s'il y avait un exemple de chat depuis 2 mois et demi... https://github.com/HE-Arc/laravel-chat :roll_eyes: 

_3 secondes plus tard_ est la mauvaise approche qu'on a un système de notifications à disposition.

* https://laravel.com/docs/5.3/broadcasting
* https://laravel.com/docs/5.3/notifications

**Comment by j4kim** [comment]
J'ai jamais réussi à l'installer votre chat 😢 
Mais ok on regardera ça si on a le time

**Comment by greut** [comment]
Ca demande de s'y plonger un moment pour installer les éléments nécessaires. C'est loin d'être simple.
