### ISSUE TITLE
Upload sample en AJAX

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/cadexmus2#48]
faire la requête de création d'un sample en ajax, puis ajouter une nouvelle track avec ce sample une fois la requête réussie

**Comment by greut** [comment]
Deux solutions :

1. faire l'upload dans une `iframe` cachée. Très simple.
2. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Submitting_forms_and_uploading_files

```html
<form target="target" enctype="multipart/form-data" method="post" action="upload.php">
	<iframe name="target" src="" style="width:0;height:0;border:0 none;" ></iframe>
	<input type="file" name="filename">
	<input type="submit" value="Upload">
</form>
```
Depuis la page d'envoi, on peut rappeler la page avec du JS `parent`.

**Comment by j4kim** [comment]
@ArnaudDroxler : j'ai fait la redirection et ajout de la ligne en pas ajax
* Redirection après l'upload sur la page du projet : https://github.com/HE-Arc/cadexmus2/commit/4710605c43756da1d16ce070d5c4e2ff16c72040#diff-757eddece9b0a683d0a7bd87daef1285R38
(`with` met le nouveau sample dans la session)
* Récupération de l'objet newSample dans le javascript : https://github.com/HE-Arc/cadexmus2/commit/4710605c43756da1d16ce070d5c4e2ff16c72040#diff-1cec4eb769ac1be34b7ccf1d3ccffda5R37
* Ajout de la nouvelle track avec le nouveau sample : https://github.com/HE-Arc/cadexmus2/commit/4710605c43756da1d16ce070d5c4e2ff16c72040#diff-4910964b52f4efbf77fad53f496e7ecdR213

Du coup si t'es chaud tu peux quand même essayer de faire ça en ajax ou alors tu peux clore l'issue

**Comment by j4kim** [comment]
Ah mais en fait la technique de l'iframe de greut risque d'être bien plus pratique, j'avais pas vu...
